# -*- mode: ruby -*-
# vi: set ft=ruby :

hosts = {
  "course-1" => "192.168.88.10",
  "course-2" => "192.168.88.11"
}

Vagrant.configure("2") do |config|
    config.ssh.insert_key = false
  # === Две существующие Ubuntu-машины ===
  hosts.each do |name, ip|
    config.vm.define name do |machine|
      machine.vm.box = "bento/ubuntu-22.04"
      machine.vm.network :private_network, ip: ip

      machine.vm.provider "virtualbox" do |v|
        v.name   = name
        v.gui    = false
        v.memory = "2048"
        v.cpus   = 1
      end

      machine.vm.provision "shell", path: "provision.sh"
    end
  end

  # === Третья машина с Issabel ===
  config.vm.define "issabel-course" do |issabel|
    issabel.vm.box = "issabel-local"
    issabel.ssh.username = "vagrant"
    issabel.ssh.private_key_path = "C:/CourseWork4Grade/id_rsa_issabel"         # имя твоего box из issabel.box
    issabel.vm.network :private_network, ip: "192.168.88.12"

    issabel.vm.provider "virtualbox" do |v|
      v.name   = "issabel-course"
      v.gui    = true                         # Issabel обычно удобнее с GUI
      v.memory = "4096"
      v.cpus   = 2
    end

    # если нужен отдельный провижининг для Issabel – свой скрипт
    # issabel.vm.provision "shell", path: "provision_issabel.sh"
  end
end
